#Program to input 8 numbers from the user and display all the unique numbers
numbers=set()
n1=int(input("Enter the first number: "))
numbers.add(n1)
n2=int(input("Enter the second number: "))
numbers.add(n2)
n3=int(input("Enter the third number: "))
numbers.add(n3)
n4=int(input("Enter the fourth number: "))
numbers.add(n4)
n5=int(input("Enter the fifth number: "))
numbers.add(n5)
n6=int(input("Enter the sixth number: "))
numbers.add(n6)
n7=int(input("Enter the seventh number: "))
numbers.add(n7)
n8=int(input("Enter the eighth number: "))
numbers.add(n8)
print(numbers)